### ISSUE TITLE
Fatal error: Class 'MetaModels\DcGeneral\Events\Table\FilterSetting\DrawSetting' not found

### ISSUE THREAD

**Issue by bibib** [cogizz/metamodelsfilter_textcombine#14]
Contao 3.3.5
metamodels/core dev-tng (5a98d965)

Habe gerade über den Composer metamodelsfilter_textcombine in der Version dev-tng (b0c17243) installiert. Wenn ich die Attributeinstellungen für meine Filtereinstellungen editieren will, erhalte ich folgende Fehlermeldung:

Fatal error: Class 'MetaModels\DcGeneral\Events\Table\FilterSetting\DrawSetting' not found in /.../.../.../.../.../composer/vendor/cogizz/metamodelsfilter_textcombine/src/system/modules/metamodelsfilter_textcombine/MetaModels/DcGeneral/Events/Table/FilterSetting/DrawTextCombineSetting.php on line 34

Was kann ich tun?

**Comment by cboelter** [comment]
Das liegt daran das der Filter aktuell nicht mit dem jetzigen Stand von MetaModels kompatibel ist.
Ich habe aktuell keinen Bedarf an dem Filter, dementsprechend wäre hier ein Sponsoring für die Korrektur ganz erfreulich :)

**Comment by cboelter** [comment]
Ich habe nun einen Sponsor gefunden und werde den Filter in der nächsten Woche lauffähig machen.

**Comment by bibib** [comment]
Ach du Schande, den Sponsoring-Aufruf hatte ich vollkommen übersehen :-(
Aber super, dass sich jetzt jemand gefunden hat. Wo und wie könnte man denn beitragen?

**Comment by cboelter** [comment]
In dem Fall wäre es jetzt per E-Mail an mich gegangen, generelle sachen bei MetaModels gehen immer über now.metamodel.me

**Comment by cboelter** [comment]
Der Fehler sollte jetzt behoben sein. Bitte testen!

**Comment by bibib** [comment]
Danke, ich habe gerade versucht zu testen.
Konnte vorerst keinen neuen Filter anlegen, gleiches Problem wie hier: https://github.com/MetaModels/core/issues/710
Habe dann, wie vorgeschlagen, den DC_General auf dev-develop aktualisiert. Dann konnte ich einen neuen Filter anlegen, nach der Auswahl des Filtertyps "Kombinierter Textfilter" erhalte ich aber folgende Fehlermeldung:
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Execute callback TableMetaModelFilterSetting_TextCombine::attrIdToName failed - Exception message: Class TableMetaModelFilterSetting_TextCombine does not exist thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Callback/Callbacks.php on line 75

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Callback/AbstractReturningCallbackListener.php(44): ContaoCommunityAlliance\DcGeneral\Contao\Callback\Callbacks::callArgs(Array, Array)
#1 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Callback\AbstractReturningCallbackListener->__invoke(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\DecodePropertyValueForWidgetEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Object(ContaoCommunityAlliance\DcGeneral\Contao\Callback\PropertyOnLoadCallbackListener), Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\DecodePropertyValueForWidgetEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\DecodePropertyValueForWidgetEvent))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\DecodePropertyValueForWidgetEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(500): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->decodeValue('textcombine_att...', '')
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(718): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->getWidget('textcombine_att...', Object(ContaoCommunityAlliance\DcGeneral\Data\PropertyValueBag))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(420): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->renderWidget('textcombine_att...', true, Object(ContaoCommunityAlliance\DcGeneral\Data\PropertyValueBag))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(665): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->buildFieldSet(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Palette), Object(ContaoCommunityAlliance\DcGeneral\Data\PropertyValueBag))
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, NULL)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#12 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#13 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#18 system/modules/core/classes/Backend.php(409): MetaModels\BackendIntegration\Module->generate()
#19 contao/main.php(142): Contao\Backend->getBackendModule('metamodels')
#20 contao/main.php(293): Main->run()
#21 {main}
```

Problem mit dem Textfilter oder mit dem DC_General?

**Comment by cboelter** [comment]
äähm hast du auch den TNG bzw. 2.0.X-dev branch genommen? Als vom textcombine ...
Die Klasse gibt es in der TNG eigentlich nicht mehr.

**Comment by bibib** [comment]
dev-tng (6df9de1f) steht da - und ich hab's hier von github geladen ... irgendwie vergesse ich immer, dass der Filter ja eh im Composer ist ...

**Comment by cboelter** [comment]
hast du den vorherigen filter auch komplett gelöscht? Ohne composer dürfte der TNG garnicht funktionieren. Also bitte einmal über composer installieren.

**Comment by bibib** [comment]
Okay, done. Filter gelöscht, Textcombine über den Composer installiert, Filter kann jetzt ausgewählt und konfiguriert werden. Ich habe dann das Modul entsprechend angepasst, bekomme aber beim Aufruf der Seite, auf der das Filtermodul eingebunden ist, eine weiße Seite mit folgender Fehlermeldung:

```
Fatal error: Call to a member function getServiceContainer() on a non-object in /.../composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/FrontendFilter.php on line 366
```
Egal ob die Einbindung per Modul oder direkt über das Inhaltselement erfolgt.

**Comment by cboelter** [comment]
Hast du dort den Clear-All defintiert?
Wenn ja einmal deaktivieren, der wirft aktuell noch nen Fehler.

**Comment by bibib** [comment]
Ja, danke, deaktivieren hat geholfen. Ich kann die Seite aufrufen, nur die Suche liefert mir nach wie vor "kein passendes Ergebnis". Fürchte aber, das liegt an mir, ich hab dasselbe Problem schon mit dem normalen Textfilter.

**Comment by cboelter** [comment]
ok, komisch ... bei interesse kannst du mir zugangsdaten mailen, dann schaue ich mir das mal an. github@boelter.eu
